# Generated by Django 2.2.14 on 2020-10-15 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20201014_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('prepared', models.BooleanField(default=False)),
                ('tracking', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique_for_month='date')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
